# Generated by Django 4.2.4 on 2023-09-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0002_performance_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='performance',
        ),
        migrations.AddField(
            model_name='performance',
            name='scenes',
            field=models.ManyToManyField(to='perform.scene'),
        ),
    ]
